version: '3.8'

services:
  app:
    build: .
    container_name: shortener_app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_URL=postgres://user:password@db:5432/shortener_db?sslmode=disable
      - REDIS_ADDR=cache:6379
    depends_on:
      - db
      - cache
    restart: on-failure

  db:
    image: postgres:16-alpine
    container_name: shortener_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  cache:
    image: redis:alpine
    container_name: shortener_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: